#!/bin/bash
apt install -y lsb-release || exit 1
apt install -y emacs vim nano || exit 1
apt install -y python-is-python3 git gitk || exit 1
echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list || exit 1
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - || exit 1
apt update || exit 1
apt install -y ros-noetic-desktop-full || exit 1
apt install -y python3-rosdep || exit 1
apt install -y ros-noetic-jackal-description ros-noetic-jackal-control ros-noetic-jackal-msgs ros-noetic-jackal-gazebo ros-noetic-jackal-navigation ros-noetic-jackal-simulator ros-noetic-jackal-tutorials ros-noetic-jackal-viz ros-noetic-opencv-apps python3-sympy || exit 1
rm -f /etc/ros/rosdep/sources.list.d/20-default.list || exit 1
rosdep init || exit 1
echo "installed!"
